# typed: false
# frozen_string_literal: true

# This file was generated by task release. DO NOT EDIT.
class Mit < Formula
  desc "Multi-repo Integration Tool. Manage multiple repositories as a unified workspace without git submodules."
  homepage "https://github.com/gabemeola/mit"
  version "0.0.2"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gabemeola/mit/releases/download/v0.0.2/mit_Darwin_arm64.tar.gz"
      sha256 "25e112a630536e1bab5856f1a1618a5fa7c7b58bce7e3ac5db1cc31649e380f7"

      def install
        bin.install "mit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gabemeola/mit/releases/download/v0.0.2/mit_Linux_x86_64.tar.gz"
      sha256 "e1a3d35538c2b5aae9aa945fcb31b350780e46ef1a0579f5b166f8731e7e6d58"

      def install
        bin.install "mit"
      end
    end

    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gabemeola/mit/releases/download/v0.0.2/mit_Linux_arm64.tar.gz"
      sha256 "f7a45f302c1391b2e629a5083748ce7e1fb838d2e82a8888770f3a9e8301801f"

      def install
        bin.install "mit"
      end
    end
  end
end
